export const REPLACE_ARTISTS = 'REPLACE_ARTISTS'
export const REPLACE_LOADING_ARTISTS = 'REPLACE_LOADING_ARTISTS'
export const REPLACE_ERROR_ARTISTS = 'REPLACE_ERROR_ARTISTS'

export const REPLACE_SONGS = 'REPLACE_SONGS'
export const REPLACE_LOADING_SONGS = 'REPLACE_LOADING_SONGS'
